export enum PackageStatus {
  REGISTERED = "REGISTERED",
  WEIGHED = "WEIGHED",
  ROUTE_ASSIGNED = "ROUTE_ASSIGNED",
  IN_STORAGE = "IN_STORAGE",
  CLASSIFIED = "CLASSIFIED",
  READY_FOR_DISPATCH = "READY_FOR_DISPATCH",
  IN_TRANSIT = "IN_TRANSIT",
  DELIVERED = "DELIVERED",
  NOVELTY = "NOVELTY",
  RETURNED = "RETURNED",
}
