/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PesajeRouteImport } from './routes/pesaje'
import { Route as NovedadesRouteImport } from './routes/novedades'
import { Route as GestionRouteImport } from './routes/gestion'
import { Route as DiscrepanciaRouteImport } from './routes/discrepancia'
import { Route as AdmisionRouteImport } from './routes/admision'
import { Route as IndexRouteImport } from './routes/index'

const PesajeRoute = PesajeRouteImport.update({
  id: '/pesaje',
  path: '/pesaje',
  getParentRoute: () => rootRouteImport,
} as any)
const NovedadesRoute = NovedadesRouteImport.update({
  id: '/novedades',
  path: '/novedades',
  getParentRoute: () => rootRouteImport,
} as any)
const GestionRoute = GestionRouteImport.update({
  id: '/gestion',
  path: '/gestion',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscrepanciaRoute = DiscrepanciaRouteImport.update({
  id: '/discrepancia',
  path: '/discrepancia',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmisionRoute = AdmisionRouteImport.update({
  id: '/admision',
  path: '/admision',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admision': typeof AdmisionRoute
  '/discrepancia': typeof DiscrepanciaRoute
  '/gestion': typeof GestionRoute
  '/novedades': typeof NovedadesRoute
  '/pesaje': typeof PesajeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admision': typeof AdmisionRoute
  '/discrepancia': typeof DiscrepanciaRoute
  '/gestion': typeof GestionRoute
  '/novedades': typeof NovedadesRoute
  '/pesaje': typeof PesajeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admision': typeof AdmisionRoute
  '/discrepancia': typeof DiscrepanciaRoute
  '/gestion': typeof GestionRoute
  '/novedades': typeof NovedadesRoute
  '/pesaje': typeof PesajeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admision'
    | '/discrepancia'
    | '/gestion'
    | '/novedades'
    | '/pesaje'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admision'
    | '/discrepancia'
    | '/gestion'
    | '/novedades'
    | '/pesaje'
  id:
    | '__root__'
    | '/'
    | '/admision'
    | '/discrepancia'
    | '/gestion'
    | '/novedades'
    | '/pesaje'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdmisionRoute: typeof AdmisionRoute
  DiscrepanciaRoute: typeof DiscrepanciaRoute
  GestionRoute: typeof GestionRoute
  NovedadesRoute: typeof NovedadesRoute
  PesajeRoute: typeof PesajeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pesaje': {
      id: '/pesaje'
      path: '/pesaje'
      fullPath: '/pesaje'
      preLoaderRoute: typeof PesajeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novedades': {
      id: '/novedades'
      path: '/novedades'
      fullPath: '/novedades'
      preLoaderRoute: typeof NovedadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestion': {
      id: '/gestion'
      path: '/gestion'
      fullPath: '/gestion'
      preLoaderRoute: typeof GestionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discrepancia': {
      id: '/discrepancia'
      path: '/discrepancia'
      fullPath: '/discrepancia'
      preLoaderRoute: typeof DiscrepanciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admision': {
      id: '/admision'
      path: '/admision'
      fullPath: '/admision'
      preLoaderRoute: typeof AdmisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdmisionRoute: AdmisionRoute,
  DiscrepanciaRoute: DiscrepanciaRoute,
  GestionRoute: GestionRoute,
  NovedadesRoute: NovedadesRoute,
  PesajeRoute: PesajeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
