/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrackingRouteImport } from './routes/tracking'
import { Route as ReportarNovedadRouteImport } from './routes/reportar-novedad'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PesajeRouteImport } from './routes/pesaje'
import { Route as NovedadesRouteImport } from './routes/novedades'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GestionRouteImport } from './routes/gestion'
import { Route as DiscrepanciaRouteImport } from './routes/discrepancia'
import { Route as ClasificacionRouteImport } from './routes/clasificacion'
import { Route as AdmisionRouteImport } from './routes/admision'
import { Route as IndexRouteImport } from './routes/index'

const TrackingRoute = TrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportarNovedadRoute = ReportarNovedadRouteImport.update({
  id: '/reportar-novedad',
  path: '/reportar-novedad',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PesajeRoute = PesajeRouteImport.update({
  id: '/pesaje',
  path: '/pesaje',
  getParentRoute: () => rootRouteImport,
} as any)
const NovedadesRoute = NovedadesRouteImport.update({
  id: '/novedades',
  path: '/novedades',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GestionRoute = GestionRouteImport.update({
  id: '/gestion',
  path: '/gestion',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscrepanciaRoute = DiscrepanciaRouteImport.update({
  id: '/discrepancia',
  path: '/discrepancia',
  getParentRoute: () => rootRouteImport,
} as any)
const ClasificacionRoute = ClasificacionRouteImport.update({
  id: '/clasificacion',
  path: '/clasificacion',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmisionRoute = AdmisionRouteImport.update({
  id: '/admision',
  path: '/admision',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admision': typeof AdmisionRoute
  '/clasificacion': typeof ClasificacionRoute
  '/discrepancia': typeof DiscrepanciaRoute
  '/gestion': typeof GestionRoute
  '/login': typeof LoginRoute
  '/novedades': typeof NovedadesRoute
  '/pesaje': typeof PesajeRoute
  '/register': typeof RegisterRoute
  '/reportar-novedad': typeof ReportarNovedadRoute
  '/tracking': typeof TrackingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admision': typeof AdmisionRoute
  '/clasificacion': typeof ClasificacionRoute
  '/discrepancia': typeof DiscrepanciaRoute
  '/gestion': typeof GestionRoute
  '/login': typeof LoginRoute
  '/novedades': typeof NovedadesRoute
  '/pesaje': typeof PesajeRoute
  '/register': typeof RegisterRoute
  '/reportar-novedad': typeof ReportarNovedadRoute
  '/tracking': typeof TrackingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admision': typeof AdmisionRoute
  '/clasificacion': typeof ClasificacionRoute
  '/discrepancia': typeof DiscrepanciaRoute
  '/gestion': typeof GestionRoute
  '/login': typeof LoginRoute
  '/novedades': typeof NovedadesRoute
  '/pesaje': typeof PesajeRoute
  '/register': typeof RegisterRoute
  '/reportar-novedad': typeof ReportarNovedadRoute
  '/tracking': typeof TrackingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admision'
    | '/clasificacion'
    | '/discrepancia'
    | '/gestion'
    | '/login'
    | '/novedades'
    | '/pesaje'
    | '/register'
    | '/reportar-novedad'
    | '/tracking'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admision'
    | '/clasificacion'
    | '/discrepancia'
    | '/gestion'
    | '/login'
    | '/novedades'
    | '/pesaje'
    | '/register'
    | '/reportar-novedad'
    | '/tracking'
  id:
    | '__root__'
    | '/'
    | '/admision'
    | '/clasificacion'
    | '/discrepancia'
    | '/gestion'
    | '/login'
    | '/novedades'
    | '/pesaje'
    | '/register'
    | '/reportar-novedad'
    | '/tracking'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdmisionRoute: typeof AdmisionRoute
  ClasificacionRoute: typeof ClasificacionRoute
  DiscrepanciaRoute: typeof DiscrepanciaRoute
  GestionRoute: typeof GestionRoute
  LoginRoute: typeof LoginRoute
  NovedadesRoute: typeof NovedadesRoute
  PesajeRoute: typeof PesajeRoute
  RegisterRoute: typeof RegisterRoute
  ReportarNovedadRoute: typeof ReportarNovedadRoute
  TrackingRoute: typeof TrackingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tracking': {
      id: '/tracking'
      path: '/tracking'
      fullPath: '/tracking'
      preLoaderRoute: typeof TrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reportar-novedad': {
      id: '/reportar-novedad'
      path: '/reportar-novedad'
      fullPath: '/reportar-novedad'
      preLoaderRoute: typeof ReportarNovedadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pesaje': {
      id: '/pesaje'
      path: '/pesaje'
      fullPath: '/pesaje'
      preLoaderRoute: typeof PesajeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novedades': {
      id: '/novedades'
      path: '/novedades'
      fullPath: '/novedades'
      preLoaderRoute: typeof NovedadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestion': {
      id: '/gestion'
      path: '/gestion'
      fullPath: '/gestion'
      preLoaderRoute: typeof GestionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discrepancia': {
      id: '/discrepancia'
      path: '/discrepancia'
      fullPath: '/discrepancia'
      preLoaderRoute: typeof DiscrepanciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clasificacion': {
      id: '/clasificacion'
      path: '/clasificacion'
      fullPath: '/clasificacion'
      preLoaderRoute: typeof ClasificacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admision': {
      id: '/admision'
      path: '/admision'
      fullPath: '/admision'
      preLoaderRoute: typeof AdmisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdmisionRoute: AdmisionRoute,
  ClasificacionRoute: ClasificacionRoute,
  DiscrepanciaRoute: DiscrepanciaRoute,
  GestionRoute: GestionRoute,
  LoginRoute: LoginRoute,
  NovedadesRoute: NovedadesRoute,
  PesajeRoute: PesajeRoute,
  RegisterRoute: RegisterRoute,
  ReportarNovedadRoute: ReportarNovedadRoute,
  TrackingRoute: TrackingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
