export enum PackageStatus {
  RECIBIDO_EN_SEDE = "RECIBIDO_EN_SEDE",
  EN_CLASIFICACION = "EN_CLASIFICACION",
  LISTO_PARA_DESPACHO = "LISTO_PARA_DESPACHO",
  EN_TRANSITO = "EN_TRANSITO",
  EN_PARADA_DE_ENTREGA = "EN_PARADA_DE_ENTREGA",
  ENTREGADO = "ENTREGADO",
  NOVEDAD_EN_BODEGA = "NOVEDAD_EN_BODEGA",
  DEVOLUCION_EN_RUTA = "DEVOLUCION_EN_RUTA",
  EXTRAVIADO_EN_RUTA = "EXTRAVIADO_EN_RUTA",
  DAÑADO_EN_RUTA = "DAÑADO_EN_RUTA",
}
